export enum Insult {
    BerceTropPresDuMur = "Tu as été bercé un peu trop près du mur, non ?",
     CacherSesPropresOeufs = "Tu pourrais cacher tes propres œufs de Pâques.",
     PoisChiche = "Tu as vraiment un pois chiche dans la tête.",
     IdeesIntelligentesSuivent = "Les idées intelligentes t'ont toujours suivi, mais tu es trop rapide.",
     LoinDerriere = "Tu es tellement loin derrière que tu es persuadé d'être le premier.",
     CouteauNonAiguise = "T'es pas le couteau le plus aiguisé du tiroir.",
     PasEncombreParLaPensee = "Tu n'es pas encombré par le processus de pensée.",
     AttenduRienDeToi = "Je n'attendais rien de toi, je suis quand même déçu.",
     SeulMaisDernier = "Si tu étais seul dans une compétition, on te présenterait quand même comme le dernier.",
     EquipeMoinsTrois = "T’avoir dans l’équipe revient à perdre trois bons travailleurs.",
     VautMieuxQueLePremierNeClamsePas = "Tu n'es pas le plus idiot du monde, mais vaut mieux pour toi que le premier ne clamse pas.",
     NeLaissePasTonCerveauMonter = "Ménage-toi, ne laisse pas ton cerveau aller jusqu’à ta tête.",
     PanneauAvertissement = "Tu es la raison pour laquelle on utilise des panneaux AVERTISSEMENT.",
     DeuxNeuronesTroisiemePlace = "Tu n’as que deux neurones et ils se battent pour la troisième place.",
     HamsterMort = "La roue tourne, mais ton hamster est visiblement décédé.",
     ConCommeLaLune = "T’es con comme la Lune.",
     BerceauFeuPelle = "Quand ton berceau a pris feu, on t’a éteint à coups de pelle.",
     PeutMeSurprendre = "À ce stade, tu ne peux que me surprendre.",
     BottesEtInstructions = "Tu ne pourrais même pas enlever l’eau d’une botte si les instructions se trouvaient sous le talon.",
     TrousDansRaquette = "Tu as quelques trous dans la raquette.",
     PasLeCouvercle = "Dans une boîte de cons, tu ne ferais même pas le couvercle.",
     PasBeurre = "T’es pas la tartine la plus beurrée du petit-dej.",
     EtageALouer = "T’es bâti comme un building mais le dernier étage est à louer.",
     IdiotDuVillage = "Si on regroupait tous les idiots du village, tu serais encore l’idiot du village.",
     ManqueDeCuisson = "Il te manque deux minutes de cuisson.",
     FourchettePourLaSoupe = "Le jour où il pleuvra de la soupe, tu seras le seul avec une fourchette.",
     QITemperatureAnale = "Ton QI est au niveau de ta température anale, et t’as pas souvent de la fièvre.",
     RemueDevantEventail = "Toi, t'es du genre à remuer la tête devant un éventail.",
     BecherDeLEau = "Tu es idiot à bêcher de l'eau.",
     ComprenetteDifficilette = "T’as la comprenette difficilette.",
     FromagePasAffiné = "T’es pas le fromage le plus affiné du terroir.",
  }
  